model_name_or_path: Qwen/Qwen3-8B
training_method: full
max_prompt_length: 8192
max_response_length: 8192
gradient_checkpointing: false
activation_offload: false
use_remove_padding: true
use_fused_kernels: true
